#pragma once

#include "PlayerScript.h"
#include "EnemyScript.h"
#include "AudioScript.h"

#include "GameManager.h"

#include "BulletLogic.h"
#include "FireLMB.h"
#include "AcidLMB.h"
#include "LightningLMB.h"
#include "EnemyManagerScript.h"
#include "PowerupManagerScript.h"
#include "AcidShield.h"

#include "FirePowerupManagerScript.h"
#include "LightningPowerupManagerScript.h"
#include "AcidPowerupManagerScript.h"
#include "FireLightningPowerupManagerScript.h"
#include "FireAcidPowerupManagerScript.h"
#include "FireballSplash.h"

#include "LightningAcidPowerupManagerScript.h"
#include "FireDashVfxScript.h"
#include "GroundCheckScript.h"
#include "PlayerManagerScript.h"
#include "AcidAirBlast.h"
#include "AcidGas.h"
#include "RoomLockScript.h"
#include "ElementBaseScript.h"
#include "EventColliderScript.h"

#include "EnemyHurtboxScript.h"
#include "EnemyBulletLogic.h"

#include "EnemyHealthScript.h"
#include "AnimationTestScript.h"
#include "ScoreManagerScript.h"
#include "PauseMenuScript.h"
#include "LoseScreenScript.h"
#include "WinScreenScript.h"
#include "UIButtonScript.h"
#include "NEW_HealthBarUIScript.h"
#include "CutSceneScript.h"
#include "ManaUIScript.h"
#include "AmmoUIScript.h"
#include "NextSceneEventColliderScript.h"
#include "Ability1Script.h"
